name: 'assign reviewers by day'
description: 'Add reviewers to pull requests for each day of the week'
author: 'masakinpo'

inputs:
  repo-token:
    description: 'A token for the repo'
    required: true
  config:
    description: 'A path for the configuration'
    default: '.github/assign-reviewers-by-day.yml'

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'user-check'
  color: 'green'
